export enum textTypes {
    TITLE_BOLD = 'TITLE_BOLD', //24PX
    TITLE_REGULAR = 'TITLE_REGULAR',
    TITLE_LIGTH = 'TITLE_LIGTH',
    SUB_TITLE_BOLD = 'SUB_TITLE_BOLD', //20PX
    SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR',
    SUB_TITLE_LIGTH = 'SUB_TITLE_LIGTH',
    BUTTON_BOLD = 'BUTTON_BOLD', //18PX
    BUTTON_REGULAR = 'BUTTON_REGULAR',
    BUTTON_LIGTH = 'BUTTON_LIGTH',
    PARAGRAPH_BOLD = 'PARAGRAPH_BOLD', //14PX
    PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR',
    PARAGRAPH_LIGTH = 'PARAGRAPH_LIGTH',
    PARAGRAPH_SMALL_BOLD = 'PARAGRAPH_SMALL_BOLD', //10PX
    PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR',
    PARAGRAPH_SMALL_LIGTH = 'PARAGRAPH_SMALL_LIGTH',
}